version: "3.8"

services:
  navidrome-server:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_LOGLEVEL: info
    volumes:
      - ./navidrome/data:/data
      - ./navidrome/music:/music:ro

  navidrome-frontend:
    build:
      context: ./frontend
    ports:
      - "4522:5000"
